id = "html-jinja"
name = "HTML-Jinja Template Support"
version = "0.0.1"
schema_version = 1
description = "Highlighting for HTML-Jinja templates."
authors = ["Jaagup Averin"]
repository = "https://github.com/JaagupAverin/html-jinja"

[grammars.jinja]
repository = "https://github.com/cathaysia/tree-sitter-jinja"
path = "tree-sitter-jinja"
commit = "07a62adf99c0f41e0cab7ab523541309a8d73dc4"

[grammars.html]
repository = "https://github.com/tree-sitter/tree-sitter-html"
commit = "bfa075d83c6b97cd48440b3829ab8d24a2319809"
